repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies:
          - fastapi
          - httpx
          - sqlalchemy
          - prometheus-client
          - structlog
          - alembic
          - types-PyYAML
        args: []
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: >-
          bash -c 'set -euo pipefail; FILES=$(printf "%s\n" "$@" | grep -E "(^|/)tests/.*\\.py$" || true); if [ -z "${FILES}" ]; then echo "No changed test files. Skipping pytest."; exit 0; fi; PYTHONPATH=. pytest --maxfail=1 -q ${FILES}'
        language: system
        types: [python]
        pass_filenames: true
        files: ^tests/.*\.py$
        stages: [pre-push]

