[storj]
type = s3
provider = Other
env_auth = false
access_key_id = jvw5fyaiu2pvuqpzu4m6przf6epa
secret_access_key = jznro76esbgilqykievefc7fyhn3ofm5vu4c2dvm6ev7ihytn3yfa
endpoint = https://gateway.us1.storjshare.io
