[storj]
type = s3
provider = Other
env_auth = false
access_key_id = jx2xqn7kudm7wrbmawc3gbcz4zpq
secret_access_key = j3fofninj2hyh6n2bqdgqrxfmnjdihvup4t3mjqlfuoielainbdmy
endpoint = https://gateway.us1.storjshare.io
