name: API Deploy

on:
  workflow_dispatch: {}

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Endpoint Artifact
        uses: actions/download-artifact@v4
        with:
          name: endpoint
          path: artifact
        continue-on-error: true
      - name: Validate Artifact Presence
        run: |
          test -f artifact/endpoint.json || { echo "missing endpoint artifact" >&2; exit 1; }
          cat artifact/endpoint.json
      - name: Extract Endpoint
        id: extract
        run: |
          python3 scripts/infra/validate_endpoint.py $(jq -r '.banano_rpc_endpoint' artifact/endpoint.json)
          echo "BANANO_RPC_ENDPOINT=$(jq -r '.banano_rpc_endpoint' artifact/endpoint.json)" >> $GITHUB_ENV
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: Terraform Init
        working-directory: infra/akash-api
        run: terraform init -input=false
      - name: Terraform Apply
        working-directory: infra/akash-api
        env:
          BANANO_RPC_ENDPOINT: ${{ env.BANANO_RPC_ENDPOINT }}
        run: terraform apply -auto-approve -input=false -var="banano_rpc_endpoint=${{ env.BANANO_RPC_ENDPOINT }}" || true
