name: API Build

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_CANONICAL: ghcr.io/mconstant/pay2slay-api
      REGISTRY_STAGING: ghcr.io/mconstant/pay2slay-api-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Derive Git SHA
        id: vars
        run: |
          GIT_SHA=$(git rev-parse HEAD)
          echo "git_sha=$GIT_SHA" >> $GITHUB_OUTPUT
          echo "short_sha=${GIT_SHA:0:12}" >> $GITHUB_OUTPUT
          echo "branch_ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Select Repository
        id: repo
        run: |
          if [ "${{ steps.vars.outputs.branch_ref }}" = "main" ]; then
            echo "repository=$REGISTRY_CANONICAL" >> $GITHUB_OUTPUT
          else
            echo "repository=$REGISTRY_STAGING" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image (single-arch, no cache)
        run: |
          docker build --no-cache --platform linux/amd64 -t ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.git_sha }} .
          docker tag ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.git_sha }} ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.short_sha }}

      - name: Capture Local Digest (pre-push)
        id: digest
        run: |
          DIGEST=$(docker image inspect ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.git_sha }} --format '{{.Id}}')
          echo "pre_push_digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Push Images
        run: |
          docker push ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.git_sha }}
          docker push ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.short_sha }}

      - name: Soft Signature Verify (placeholder)
        id: sign
        run: |
          echo "signature_status=unverified" >> $GITHUB_OUTPUT
          echo "signature_reason=missing" >> $GITHUB_OUTPUT

      - name: Install Project
        run: |
          pip install .

      - name: Emit Metadata JSON
        id: meta
        run: |
          python scripts/ci/emit_image_metadata.py \
            --sha ${{ steps.vars.outputs.git_sha }} \
            --repository ${{ steps.repo.outputs.repository }} \
            --digest ${{ steps.digest.outputs.pre_push_digest }} > metadata.json
          echo "metadata_path=metadata.json" >> $GITHUB_OUTPUT
          echo "pre_push_digest=${{ steps.digest.outputs.pre_push_digest }}" >> $GITHUB_OUTPUT

      - name: Upload Metadata Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-metadata
          path: metadata.json

      - name: Log Summary
        run: |
          echo "Built image ${{ steps.repo.outputs.repository }}:${{ steps.vars.outputs.git_sha }} digest=${{ steps.digest.outputs.pre_push_digest }} signature=${{ steps.sign.outputs.signature_status }}"
